# Домашняя работа "Продвинутый pandas"

## Задание 1

Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:  
  
если источник traffic_source равен yandex или google, то в source_type ставится organic  
для источников paid и email из России - ставим ad  
для источников paid и email не из России - ставим other  
все остальные варианты берем из traffic_source без изменений

In [27]:
import pandas as pd
log = pd.read_csv('visit_log.csv', sep=';')
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [34]:
log.loc[((log.traffic_sou)rce.isin(['yandex' ,'google'])), 'traffic_type'] = 'organic'
log.loc[(log.traffic_source.isin(['paid' ,'email'])), 'traffic_type'] = 'other'
log.loc[(log.traffic_source.isin(['paid' ,'email']) & (log.region == 'Russia')), 'traffic_type'] = 'ad'
log.loc[pd.isnull(log.traffic_type), 'traffic_type'] = log.traffic_source
log.head(100)

,timestamp,visit_id,url,region,user_id,traffic_source,traffic_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
...,...,...,...,...,...,...,...
95,1549981294,8542681424,https://host.ru/f1eb4601740d627ab0,Russia,9310ce3130,paid,ad
96,1549981298,2ea9ab9198,https://host.ru/9f90e5c423a5f976d4,Ukraine,e9b6323d51,email,other
97,1549981308,136dd1a7d0,https://host.ru/1be58f19f26458f2fe,Russia,e0c3978e3a,direct,direct
98,1549981312,30274f1a3e,https://host.ru/5301a605bd574af1a5,Russia,691be7fee0,google,organic
99,1549981324,4b298058e1,https://host.ru/b8b58337d272ee7b15,Belarus,4d4a578a01,direct,direct

## Задание 2

В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:  
  
Прочитайте содержимое файла с датафрейм  
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [39]:
urls = pd.read_csv('URLs.txt')
urls.head()

                                                 url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [42]:
urls[urls.url.str.contains('\/\d{8}-',  regex=True)].head()

                                                 url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...

## Задание 3

В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [106]:
from pymystem3 import Mystem
m = Mystem()

In [107]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})
data.head()

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [108]:
data['lemmas'] = data['keyword'].apply(lambda x: ' '.join(m.lemmatize(x)).strip())
data.head()

                 keyword   shows                     lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль
1        доллары в рубли  114173         доллар   в   рубль
2  100 долларов в рублях   97534   100   доллар   в   рубль
3             курс рубля   53546               курс   рубль